- README.md
Since I brought up the issue, I'm contributing a small update to the README. Feel free to reword / integrate. Not sure how would you add to the integration page? Please assist.
> Adds warning for privilege escalation by collaborators, fixes #12

- index.js
- package-lock.json
- package.json
- test/index.js
Merge event and context variable from https://github.com/probot/probot/pull/158
> Use just context variable

- .github/settings.yml
- README.md
- lib/plugins/repository.js
- package-lock.json
- test/settings.js
Fixes #26 
```yml
repository:
topics: github, probot
```
> Add support for topics

- index.js
- lib/plugins/collaborators.js
- lib/plugins/diffable.js
- lib/plugins/labels.js
- lib/plugins/repository.js
- lib/plugins/teams.js
- lib/settings.js
- package-lock.json
- package.json
- test/index.js
- test/settings.js
Re: https://github.com/probot/probot/issues/235
> Use standard for linting

- package.json
- test/index.test.js
- test/mocha.opts
- test/settings.test.js
Migrate to Jest, https://github.com/probot/probot/issues/288.
It won't let me ask for a review from @probot/maintainers but y'all can review it.
> Migrate to Jest

- test/settings.test.js
- _descripton_ is not _description_
> Trivial: fix typo in test file

- lib/plugins/labels.js
- test/lib/plugins/labels.test.js
> Fix label color issue

- README.md
- lib/plugins/milestones.js
- lib/settings.js
- test/lib/plugins/milestones.test.js
> Add milestones configuration

- README.md
- index.js
- lib/mergeArrayByName.js
- package.json
- test/index.test.js
- test/lib/mergeArrayByName.test.js
This is dependent on https://github.com/probot/probot-config/pull/22 getting merged. 
-----
[View rendered README.md](https://github.com/jwsloan/settings/blob/merge-by-name/README.md)
> feat: Add mergeByName

- README.md
- lib/plugins/labels.js
- test/lib/plugins/labels.test.js
> Add support for label descriptions

- .gitignore
- package-lock.json
- test/index.test.js
this gets gets master back to a passing state. i also started versioning the lock file to prevent time alone from introducing similar breakages
> Get contents stub

- lib/plugins/collaborators.js
- lib/plugins/repository.js
- lib/plugins/teams.js
- lib/settings.js
- test/lib/plugins/collaborators.test.js
- test/lib/plugins/repository.test.js
- test/lib/plugins/teams.test.js
See here: https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations
> Fixed octokit/rest.j sv15.18 deprecations

- README.md
also, i don't seem to be able to add @jwsloan as a reviewer. are additional permissions needed for that?
-----
[View rendered README.md](https://github.com/travi/settings/blob/readme-sections/README.md)
> Improve readability of key readme sections

- package-lock.json
- package.json
> Added nodemon integration

- README.md
This PR
💁‍♂ For reference, see https://developer.github.com/v3/repos/branches/#parameters-1. 
-----
[View rendered README.md](https://github.com/localheinz/settings/blob/feature/apps/README.md)
> Enhancement: Add apps to list of restrictions

- README.md
-----
[View rendered README.md](https://github.com/travi/settings/blob/travis-badge/README.md)
> docs(badges): added a travis badge

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
in hopes that is the detail needed to trigger proper prompting when opening a new issue
closes #174
-----
[View rendered .github/ISSUE_TEMPLATE/bug.md](https://github.com/travi/settings/blob/about-issue-templates/.github/ISSUE_TEMPLATE/bug.md)
[View rendered .github/ISSUE_TEMPLATE/feature.md](https://github.com/travi/settings/blob/about-issue-templates/.github/ISSUE_TEMPLATE/feature.md)
> docs(issue-templates): added about to each template

- package-lock.json
- package.json
- test/integration/push.test.js
and depended on a specific version, so that greenkeeper will send PRs for each new version. probot
is pretty core to operation, so seems like we should keep it up to date
> fix(dependencies): upgraded probot

- lib/plugins/repository.js
- test/fixtures/config.yml
- test/integration/push.test.js
- test/unit/lib/plugins/repository.test.js
> feat(repo-template): enabled the preview to allow toggling the flag

- lib/settings.js
- test/integration/push.test.js
the response was unused since the config was used from the previous load using context.config
> perf(config-fetch): removed the unused fetch of the config file

- test/fixtures/milestones-config.yml
- test/integration/push.test.js
> test(integration): pinned milestones sync behavior

- lib/plugins/milestones.js
- package-lock.json
- package.json
- test/fixtures/milestones-config.yml
- test/integration/push.test.js
since providing extra attributes results in a 422 - Unprocessable Entity, preventing the milestones from being successfully updated
fixes #225
> fix(milestones): limited the repo details included in the requests

- docs/deploy.md
-----
[View rendered docs/deploy.md](https://github.com/travi/settings/blob/permissions/docs/deploy.md)
> docs(deploy): updated the required permissions and events

- README.md
now that they are all available through the api
closes #158
-----
[View rendered README.md](https://github.com/travi/settings/blob/permission/README.md)
> docs(permission): updated the available options

- lib/plugins/teams.js
- package-lock.json
- package.json
- test/integration/push.test.js
- test/unit/lib/plugins/teams.test.js
since the modern endpoints for .com dont exist on versions of ghe that are not yet EOL
fixes #235
> fix(teams): called endpoints that exist on github enterprise

- .github/workflows/node-ci.yml
- .travis.yml
- README.md
-----
[View rendered README.md](https://github.com/travi/settings/blob/gh-actions/README.md)
> ci: switched from Travis-CI to GH Actions

- test/integration/collaborators.test.js
- test/integration/common.js
- test/integration/milestones.test.js
- test/integration/push.test.js
- test/integration/repository.test.js
- test/integration/teams.test.js
> test(integration): split the push test into plugin tests

- test/integration/common.js
- test/integration/plugins/collaborators.test.js
- test/integration/plugins/milestones.test.js
- test/integration/plugins/repository.test.js
- test/integration/plugins/teams.test.js
- test/integration/triggers/push.test.js
- test/integration/triggers/repository-edited.test.js
> verified behavior based on both existing trigger events

- index.js
- test/integration/common.js
- test/integration/plugins/collaborators.test.js
- test/integration/plugins/milestones.test.js
- test/integration/plugins/repository.test.js
- test/integration/plugins/teams.test.js
- test/integration/triggers/push.test.js
- test/integration/triggers/repository-created.test.js
- test/integration/triggers/repository-edited.test.js
- test/unit/index.test.js
depends on #260. please don't merge before that one
> added trigger for syncing based on the repository.created event

- package-lock.json
- package.json
- test/integration/plugins/collaborators.test.js
- test/integration/plugins/milestones.test.js
- test/integration/plugins/repository.test.js
- test/integration/plugins/teams.test.js
- test/integration/triggers/repository-created.test.js
- test/integration/triggers/repository-edited.test.js
- test/unit/index.test.js
Depends on https://github.com/probot/probot/pull/1250
> fix(package): probot v10

- README.md
- package.json
- test/fixtures/collaborators-config.yml
- test/fixtures/teams-config.yml
- test/integration/common.js
- test/integration/plugins/collaborators.test.js
- test/integration/plugins/teams.test.js
adds failing tests for new permissions levels that will be unblocked after probot is upgraded to the latest octokit
> New permissions

- test/fixtures/repository/basic-config-with-topics.yml
- test/integration/plugins/repository.test.js
based on lacking coverage that could have prevented some of the changes needed in #386
> test(integration): backfilled coverage for repositories with topics defined

- README.md
Add proper documentation for the closed issue https://github.com/probot/settings/issues/134
-----
[View rendered README.md](https://github.com/dudicoco/settings/blob/patch-1/README.md)
> Document delete_branch_on_merge

- README.md
-----
[View rendered README.md](https://github.com/micimize/settings/blob/patch-1/README.md)
> Replace link to archived probot-config with octokit-plugin-config

- .github/workflows/node-ci.yml
> ci(workflow): use npm ci in node-cli.yml

- .renovaterc.json
> ci(renovate): extended the application config from form8ion

- .github/workflows/release.yml
- .releaserc.json
- package.json
based on https://github.com/wip/app/blob/master/.github/workflows/release.yml
closes #614
> ci(release): defined a release workflow

- lib/plugins/labels.js
- test/fixtures/labels-config.yml
- test/integration/plugins/labels.test.js
and added an integration test for configuring labels
for #145, for #259
> fix(labels): fixed the color padding when code has leading zeros

- test/integration/common.js
- test/integration/plugins/collaborators.test.js
- test/integration/plugins/milestones.test.js
- test/integration/plugins/repository.test.js
- test/integration/plugins/teams.test.js
- test/integration/triggers/push.test.js
- test/integration/triggers/repository-created.test.js
- test/integration/triggers/repository-edited.test.js
> test(load): handled that loading the instance is async

- README.md
- lib/plugins/environments.js
- lib/settings.js
- package.json
- test/fixtures/environments-config.yml
- test/integration/plugins/environments.test.js
- test/unit/lib/plugins/environments.test.js
Fixes #607
I tested this manually (using a private GitHub App + [test repo](https://github.com/rlmartin/test-repository-settings-app) + smee.io) and it works.
> feat: Add support for environments

- package.json
- test/integration/common.js
> test(integration): disabled throttle and retry for integration tests

- test/integration/common.js
- test/integration/plugins/collaborators.test.js
- test/integration/plugins/environments.test.js
- test/integration/plugins/labels.test.js
- test/integration/plugins/milestones.test.js
- test/integration/plugins/repository.test.js
- test/integration/plugins/teams.test.js
> test(integration): extracted common logic for setting up the proper settings content for each scenario

- lib/plugins/rulesets.js
- test/integration/features/step_definitions/rulesets-steps.js
- test/unit/lib/plugins/rulesets.test.js
> fix(rulesets): account for details like `rules` not being included in the list response
