repository-settings/app

- lib/settings.js
Fixes issue where untrusted yaml file could contain JavaScript: https://github.com/nodeca/js-yaml#safeload-string---options-
> Use yaml.safeLoad instead of load

- README.md
Add information/suggestion to users to use the GitHub CodeOwners feature to preserve permissions until in-app restrictions are implemented
Address issue #64
> Add Guidance on How to Preserve Permission Levels

- index.js
- lib/settings.js
- package.json
- test/index.test.js
This PR fixes #89 and implements support for [probot/config](https://github.com/probot/probot-config)
I have also reformatted `robot.on` within `index.js` to use an arrow function, as per most other probot apps. I've started playing around with changing the `module.exports` statement to be more in line with other probot apps by doing something like:
```js
const getConfig = require('probot-config')
const Settings = require('./lib/settings')
module.exports = robot => {
robot.on('push', async context => {
<rest_of_function>
})
}
```
but that started causing test failures I have not yet diagnosed. If that's something that makes sense to add to this PR I'm happy to dig in a bit more.
> Add support for probot-config

- lib/plugins/repository.js
- test/lib/plugins/repository.test.js
To access the `topics` property for repositories the `Accept` header must contain a custom media type referencing the `mercy-preview`.
> Added preview 'mercy'

- README.md
Relates to #150. It's not a fix, but at least document how to workaround it.
-----
[View rendered README.md](https://github.com/renatocaval/settings/blob/patch-1/README.md)
> Document workaround for branch protection settings

- README.md
* Also remove the previous example. It was redundant                                                                                                
* Points back to the main config example   
The sentence "Otherwise, none of the settings will be applied" is important because it's not obvious that the whole settings will be silently ignored. 
Relates to #151
-----
[View rendered README.md](https://github.com/renatocaval/settings/blob/fix-branch-protection-take2/README.md)
> Move note on branch protection to a callout

- lib/plugins/milestones.js
- test/lib/plugins/milestones.test.js
Changes:
- converted getMilestones call to use listMilestonesForRepo
- added paginated results for edge cases where there are more than 100 milestones
- updated the api calls to use "milestone_number" instead of "number" field to adhere to the octokit/rest.js [documentation](https://octokit.github.io/rest.js/#octokit-routes-issues-update-milestone)
Issues:
fixes https://github.com/probot/settings/issues/153
> Fixed getMilestones errors and updated api fields

- lib/plugins/teams.js
- test/lib/plugins/teams.test.js
Changes:
- corrected field names `id` to `team_id` and `org` to `owner`
Fixes #160
> Fixing teams plugin bug with incorrect field names

- lib/plugins/labels.js
- test/lib/plugins/labels.test.js
Changes:
- Added pagination for `listLabelsForRepo()` in edge cases where the number of labels is greater than 100
Fixes #166
> Added pagination for getting labels

- lib/plugins/milestones.js
Changes:
- set per_page value to 100, to reduce the number of requests made while paginating.
I forgot to do this in #156 and realized this when doing the pagination for labels at #168. Also, the default per_page value is different among requests stated [here](https://developer.github.com/v3/guides/traversing-with-pagination/#basics-of-pagination).
> specified per_page to be 100 in milestones pagination

- lib/plugins/teams.js
- test/lib/plugins/teams.test.js
Changes
- Instead of using custom pagination, I cleaned it up to use the built-in pagination from Octokit. 
This also fixes the first error found in https://github.com/probot/settings/issues/172
> Fixing pagination in teams plugin

- lib/plugins/teams.js
- test/lib/plugins/teams.test.js
Changes
- Changed `id` to `team_id` in the remove repo function call
This should fix the second error in https://github.com/probot/settings/issues/172
> fixed team_id field in removing team permissions

- package-lock.json
- package.json
and leveraged npm-run-all to simplify splitting `npm test` into multiple scripts
> Add linting for the lockfile and engines

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
im sure these will be tweaked more over time, but hoping this will get some more useful information
to be included up front
closes #174
-----
[View rendered .github/ISSUE_TEMPLATE/bug.md](https://github.com/travi/settings/blob/issue-templates/.github/ISSUE_TEMPLATE/bug.md)
[View rendered .github/ISSUE_TEMPLATE/feature.md](https://github.com/travi/settings/blob/issue-templates/.github/ISSUE_TEMPLATE/feature.md)
> docs(issue-templates): added initial bug and feature-request templates

- .github/ISSUE_TEMPLATE/feature.md
which is what i originally intended, but accidentally used the wrong comment syntax for markdown
for #174
-----
[View rendered .github/ISSUE_TEMPLATE/feature.md](https://github.com/travi/settings/blob/issue-template-comment/.github/ISSUE_TEMPLATE/feature.md)
> docs(issue-templates): switch the note to a comment

- lib/plugins/collaborators.js
- test/integration/push.test.js
since listing all does not align well with the goals of this configuration. `direct` might also be
reasonable option, but this seems like the most likely fit (see
https://developer.github.com/v3/repos/collaborators/#list-collaborators)
BREAKING CHANGE: repositories relying on comparing to the list of all collaborators will no longer
sync the same way, but that use case seems very unlikely. please open an issue to let us know if you
were relying on this behavior
fixes #155
> fix(outside-collaborators): limited the requested list to outside

- lib/plugins/branches.js
- test/unit/lib/plugins/branches.test.js
The branches settings have a subtle error where a map call doesn't actually map into anything but rather creates floating Promises. This PR returns the Promise so that promise rejections can be handled properly in calling code
> fix: return promises in map call to prevent floating promises

- .dependabot/config.yml
- README.md
i think dependabot probably makes the most sense for this particular project for managing updates going forward, but am open to further thoughts. if we do move forward in this direction, i need help actually disabling greenkeeper and enabling dependabot
-----
[View rendered README.md](https://github.com/travi/settings/blob/dependabot/README.md)
> Dependabot

- docs/deploy.md
this is needed for managing team access to a repository
-----
[View rendered docs/deploy.md](https://github.com/probot/settings/blob/org-members/docs/deploy.md)
> docs(permissions): documented that R&W is necessary for organization members

- README.md
- lib/plugins/repository.js
- test/fixtures/repository-config.yml
- test/fixtures/repository/basic-config-with-security-fixes.yml
- test/fixtures/repository/basic-config-with-vulnerability-alerts.yml
- test/fixtures/repository/basic-config.yml
- test/integration/plugins/repository.test.js
- test/unit/lib/plugins/repository.test.js
Fixes #230
-----
[View rendered README.md](https://github.com/aaricpittman/settings/blob/vulnerability-alerts/README.md)
> Support Vulnerability Alerts and Automated Security Fixes

- README.md
This proposes a tweak to the README so that folks know that `required_linear_history` is available without resorting to  issue spelunking.
This has been requested at least twice:
* #220 (this may have been related to the enhancement, to be fair)
* #292 
I'm open to this turning into an "Add additional supported options to README" PR.
> Document additional branch protection option in README (required_linear_history)

- lib/plugins/branches.js
- lib/plugins/repository.js
- test/unit/lib/plugins/branches.test.js
- test/unit/lib/plugins/repository.test.js
we should try to cover more code with integration tests without mocking methods that no longer exist @travi
I went through the unit tests and compared the mocks to the changelogs at https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/v4.0.0, I think we should be good now
> fix: `octokit.repos.replaceTopics` is now `octokit.repos.replaceAllTopics`

- README.md
I get a couple invites to repositories every week from people who copy and paste this config. This PR comments out the example collaborators so people have to at least intentionally uncomment it to invite me and @hubot.
-----
[View rendered README.md](https://github.com/bkeepers/settings/blob/patch-1/README.md)
> docs: Comment out collaborators in example

- README.md
- lib/plugins/labels.js
- package-lock.json
- test/unit/lib/plugins/labels.test.js
Supports the current API for renaming labels, which expects the following keys in `settings.yml`:
```yaml
labels:
- name: the old/current name of an existing label we want to change
new_name: the updated label name
```
Details of this API change are documented here: https://github.com/probot/settings/pull/143#issuecomment-539307068
- Fixes #407 
- Fixes #167 in a dumb way — by passing the attributes needed by the API. The previous `oldname` attribute is no longer supported.
-----
[View rendered README.md](https://github.com/elstudio/probot-settings/blob/rename-labels/README.md)
> Fix renaming of labels

- README.md
a bit overdue, but pointing to the modern docs site
-----
[View rendered README.md](https://github.com/travi/settings/blob/docs/README.md)
> docs(links): updated links to point to new docs site

- .github/workflows/node-ci.yml
Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾
> ci(workflow): add cache to workflows using actions/setup-node

- .github/settings.yml
i figure that we should activate the app on our own repo again, but we need this to be up to date before that, so the repo doesnt get renamed
> ci: updated the repo name to match the recent update

- .releaserc.json
since we only intended to disable for the initial release
> ci(release): re-enabled the success comment

- docs/configuration.md
- docs/plugins/branches.md
- docs/plugins/collaborators.md
- docs/plugins/environments.md
- docs/plugins/labels.md
- docs/plugins/milestones.md
- docs/plugins/repository.md
- docs/plugins/teams.md
> docs(configuration): split the configuration example to separate pages per plugin

- docs/plugins/environments.md
- lib/plugins/environments.js
- test/integration/features/step_definitions/environments-steps.mjs
- test/unit/lib/plugins/environments.test.js
* Added `type` support for environment `deployment_branch_policy`  custom branches.
* Environment `deployment_branch_policy` supports custom branches type - `branch` or `tag`. The type is an option parameter that sets `branch` by default. These changes allow us to specify deployment_branch_policy for  `tag` 
```yaml
environments:
- name: development
deployment_branch_policy:
custom_branches:
- dev/*
- name: release/*
type: branch
- name: v*
type: tag
```
You can specify `custom_branches` list item as `string` for back-compatibility or as object
```yaml
name: `string`
type: `branch | tag`
```
* [Create a deployment branch policy API](https://docs.github.com/en/rest/deployments/branch-policies?apiVersion=2022-11-28#create-a-deployment-branch-policy)
> feat(environments): custom branch policies support type ('branch', 'tag')

- docs/plugins/rulesets.md
- index.js
- lib/plugins/rulesets.js
- lib/settings.js
- package-lock.json
- package.json
- test/integration/features/rulesets.feature
- test/integration/features/step_definitions/rulesets-steps.mjs
- test/unit/lib/plugins/rulesets.test.js
while still WIP for ergonomics, this is production ready, but with the potential for breaking changes before considered ready for full release. my plan is to release it semi-dark so that it can be used, but without highlighting it beyond the release notes or the specific docs page (which warns about the potential for breakages)
for #732
> feat(rulesets): initial support repository rulesets (semi-dark release with the potential for breaking changes)

- docs/plugins/rulesets.md
This commit fixes the example in the ruleset documentation, which was missing the `strict_required_status_checks_policy` key. According to GitHub API documentation[1], this is a required field so it needs to be defined in the configuration file (at least at this point in time).
[1]: https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#create-a-repository-ruleset
> docs(rulesets): fix ruleset status checks example

- lib/plugins/rulesets.js
- test/integration/features/step_definitions/rulesets-steps.js
- test/unit/lib/plugins/rulesets.test.js
> fix(rulesets): filter organization rulesets from the list compared for the repository

- lib/plugins/rulesets.js
- test/integration/features/rulesets.feature
- test/integration/features/step_definitions/rulesets-steps.js
by filtering ruleset state properties from api response that do not get updated from the config
for #732
> fix(rulesets): avoid updates when no meaningful change is made
